#!/bin/bash

docker buildx inspect mybuilder || docker buildx create --name mybuilder
docker buildx use mybuilder
docker buildx build --platform linux/arm64,linux/amd64 --push --tag huynhminhdang/openvpn-tinyproxy .
