#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

realpath() {
  [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

PROXY_PORT=8888
OVPN_CONFIG=$(realpath "$1")
OVPN_PASSWD=$(realpath "$1").passwd

container_name=$( docker ps --filter ancestor=openvpn-tinyproxy --format '{{.Names}}' )
if [ -n "$container_name" ]; then
  docker kill $container_name
fi

if [ ! -f "$OVPN_PASSWD" ]; then
  echo -n Enter VPN password:
  read -s OVPN_PASSWD
  echo
fi

docker run \
  --volume "$OVPN_CONFIG:/etc/openvpn/config:ro" \
  --volume "$OVPN_PASSWD:/etc/openvpn/passwd:ro" \
  --volume "$DIR/tinyproxy.conf:/etc/tinyproxy.conf:ro" \
  --volume "$DIR/entrypoint.sh:/entrypoint.sh:ro" \
  --device /dev/net/tun \
  --cap-add NET_ADMIN \
  --publish $PROXY_PORT:8888 \
  --rm \
  --tty \
  --detach \
  openvpn-tinyproxy \
  $OVPN_PASSWD
