#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

realpath() {
  [[ $1 = /* ]] && echo "$1" || echo "$PWD/${1#./}"
}

PROXY_PORT=8888
OVPN_CONFIG_FILE=$(realpath "$1")
OVPN_PASSWD_FILE=$(realpath "$1").passwd

container_name=$( docker ps --filter ancestor=openvpn-tinyproxy --format '{{.Names}}' )
if [[ -n "$container_name" ]]; then
  docker kill $container_name
fi

args=
args+=" --volume $OVPN_CONFIG_FILE:/etc/openvpn/config:ro"
if [[ -f "$OVPN_PASSWD_FILE" ]]; then
  args+=" --volume $OVPN_PASSWD_FILE:/etc/openvpn/passwd:ro"
else
  echo -n Enter VPN password:
  read -s OVPN_PASSWD
  echo
  args+=" --env OVPN_PASSWD=$OVPN_PASSWD"
fi
args+=" --volume $DIR/entrypoint.sh:/entrypoint.sh"
args+=" --volume $DIR/etc/tinyproxy/tinyproxy.conf:/etc/tinyproxy/tinyproxy.conf"
args+=" --volume $DIR/etc/hosts.slow:/etc/hosts.slow"
args+=" --volume $DIR/etc/hosts.resolved:/etc/hosts.resolved"
args+=" --device /dev/net/tun"
args+=" --cap-add NET_ADMIN"
args+=" --publish $PROXY_PORT:8888"
args+=" --rm"
args+=" --tty"
args+=" --detach"
for flag in "$@"; do
  case "$flag" in
    -r)
      args+=" --env RESOLVE_HOSTS=1"
      ;;
  esac
done

docker run $args openvpn-tinyproxy
